Eslint
AlexRzhk/react-admin-panel pull request #1
Opened 2022-09-13 09:40 UTC by AlexRzhk

2022-09-13 10:02 UTC, AlexRzhk commented
тестировал работоспособность в клоне репозитория, для проверки prettier добавлял новые строчки в css файле между свойствами внутри селектора, для тестирования работы eslint добавлял строчку let a; в файл App.jsx, по результатам проверки, с дополнительной строкой коммит не проходил.

2022-09-13 10:03 UTC, AlexRzhk commented
в css файле prettier стирал все добавленные строки кроме одной.

2022-09-13 20:31 UTC, Muslik requested changes

2022-09-13 20:31 UTC, Muslik commented on .lintstagedrc.json
> +  "src/*.jsx": "eslint"
Можно сокращать:
```
"*.{js,jsx}": ["prettier --write", "eslint --fix"]
```

2022-09-13 20:31 UTC, Muslik commented on .lintstagedrc.json
> +  "src/*.jsx": "eslint"
У вас не запускается prettier для js/jsx файлов

2022-09-20 12:38 UTC, Muslik approved these changes

2022-09-20 16:04 UTC, merged