header and filters created
AlexRzhk/react-admin-panel pull request #2
Opened 2022-11-01 09:39 UTC by AlexRzhk

2022-11-05 01:03 UTC, Muslik requested changes
Раз уж вы используете propTypes исправьте все ошибки в консоли браузера.
Убрать redux из этого ДЗ.
Установите готовую библиотеку classnames
Всю убработку стилей переписать используя ее, а не if, split и тд.

2022-11-05 01:03 UTC, Muslik commented on package.json
> +    "@reduxjs/toolkit": "^1.8.6",
В этом ДЗ не должно быть redux-а

2022-11-05 01:03 UTC, Muslik commented on src/elements/Button/Button.jsx
> +      "full-width": isFullWidth,
В js только camelCase

2022-11-05 01:03 UTC, Muslik commented on src/elements/Button/Button.jsx
> +    buttonStyles += classNames(split(className));
Всю эту конструкцию можно сделать в одном вызове classnames. Для чего вы сплитите вообще строку

2022-11-05 01:03 UTC, Muslik commented on src/elements/Dropdown/OrderDelete/OrderDelete.jsx
> +  return (
Ни этот dropdown, ни dropdown-ы ниже не должны быть в общих компонентах. В чате я примерно показывал реализацию Dropdown которые можно переиспользовать

2022-11-05 01:03 UTC, Muslik commented on src/elements/Input/Input.jsx
> +  componentStyles += classNames(
Все в одном classnames:

```javascript
const inputClass = cx(styles._, className {[styles.incorrect]: isIncorrect })
```

2022-11-05 01:03 UTC, Muslik commented on src/elements/Input/Input.jsx
> +  resetValue = noop,
onReset

2022-11-05 01:03 UTC, Muslik commented on src/elements/Input/Input.jsx
> +        <div className={styles["wrapper"]}>
styles.wrapper
Исправить везде.

2022-11-05 01:03 UTC, Muslik commented on src/elements/icons/icons.jsx
> +Icon.propTypes = {
Компонент с большой буквы. Файл должен называться Icon.jsx, css modules тоже - Icon.module.css

2022-11-05 01:03 UTC, Muslik commented on src/utils/classnames.js
> +export function classNames(obj = {}, styles) {
Есть готовая библиотека. Нет смысла писать свое решение

2022-11-05 01:03 UTC, Muslik commented on src/features/Filter/AdditionalFilter/DateFilter/DateFilter.jsx
> +      <Input
В ваши инпуты не могу ничего ввести. Нужен onChange

2022-11-05 01:03 UTC, Muslik commented on src/features/Header/Header.jsx
> +  const theme = useSelector((state) => state.theme.value);
Для этого не нужен redux. Можно в контексте держать

2022-11-05 01:03 UTC, Muslik commented on src/features/Header/Header.jsx
> +    dispatch(changeFilterVisibility());
Мне в этом ДЗ не требуется чтобы все фильтры работали и фильтровали. Поэтому нет никакого смысла в redux на этом этапе. Просто используйте state

2022-11-05 01:03 UTC, Muslik commented on src/features/Header/Header.jsx
> +
```javascript
useEffect(() => {
  // тут делаете обработку выставленной темы
  // document.body...
}, [theme])
```

2022-11-11 13:12 UTC, AlexRzhk commented
добавил общий dropdown, используемые dropdown перенес по месту использования, неиспользуемые пока лежат в shared, по мере написания таблицы перенесу их в правильное место.

2022-11-11 19:01 UTC, Muslik commented
Убрать redux часть из этого дз

2022-11-11 19:11 UTC, Muslik requested changes

2022-11-11 19:11 UTC, Muslik commented on src/elements/Dropdown/OrderDelete/OrderDelete.jsx
> +export function OrderDelete({
Не имеет отношения к общим компонентам.

2022-11-11 19:11 UTC, Muslik commented on src/elements/Dropdown/PageSelector/PageSelector.jsx
> +export function PageSelector() {
Не имеет отношения к общим компонентам.

2022-11-11 19:11 UTC, Muslik commented on src/elements/Dropdown/PageSelector/PageSelector.jsx
> +  let PageSelectorClassName = cn(styles._, styles["page-number-choose"]);
const,

Мы не используем kebabCase. Только camelCase !

2022-11-11 19:11 UTC, Muslik commented on src/App.jsx
> +    Новый: false,
Вы не можете храните стейт на русском языке. only english

2022-11-11 19:11 UTC, Muslik commented on src/elements/icons/Icon.jsx
> +      return <Search className={styles._ + " " + styles.search} />;
classnames библиотека!

2022-11-11 19:11 UTC, Muslik commented on src/elements/Button/Button.jsx
> +let noop = () => {};
Везде если переменная неизменяемая меняем let на const!

2022-11-11 19:11 UTC, Muslik commented on src/App.jsx
> +    Новый: false,
Статусы должны быть массивом.
Статус выбран, добавляете в массив. Статус не выбран, убираете из массива:

Пример:
```javascript
const statuses = ['new', 'confirmed']
```

2022-11-11 19:11 UTC, Muslik commented on src/features/Filter/AdditionalFilter/StatusFilter/StatusFilter.jsx
> +  let statusFilterStyles = cn(styles._, className);
let на const везде.

2022-11-17 16:15 UTC, Muslik approved these changes

2022-11-18 08:20 UTC, merged